### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by imAmiee** [jys5609/DSTC5#1]
I am using theano 0.8.2 keras 1.2.1 and python 2.7

When I run my code, it shows some error.
Yields the following error message:

`Using Theano backend.
('LSTM units: ', 100)
('Learning rate: ', 0.005)
('Dropout: ', 0.0, 0.0)
--------------------------------
Weight file : dstc5_lstm100_lr005_dr0_0.h5
Train on 4296 samples, validate on 253 samples
Epoch 1/100
4096/4296 [===========================>..] - ETA: 8s - loss: -0.0286 - out_embed_loss: -0.0286 - out_prob_loss: 2.0556e-05 Epoch 00000: val_loss improved from inf to -0.03195, saving model to dstc5_lstm100_lr005_dr0_0.h5
Traceback (most recent call last):
  File "D:/dialog system/corpus/DSTC5/git_DSTC5-master/train.py", line 58, in <module>
    main(sys.argv)
  File "D:/dialog system/corpus/DSTC5/git_DSTC5-master/train.py", line 55, in main
    model.train(train_X, train_X_ins, train_Y, dev_X, dev_X_ins, dev_Y, args.nb_epoch, weight_file)
  File "D:\dialog system\corpus\DSTC5\git_DSTC5-master\model.py", line 223, in train
    self.model.fit([X, X_ins, train_info_loc], [Y, train_temp_prob], batch_size=256, nb_epoch=nb_epoch, validation_split=0., validation_data=([valid_X, valid_X_ins, valid_info_loc], [valid_Y, valid_temp_prob]), verbose=1, callbacks=[checkpointer])
  File "D:\Anaconda2\lib\site-packages\keras\engine\training.py", line 1192, in fit
    initial_epoch=initial_epoch)
  File "D:\Anaconda2\lib\site-packages\keras\engine\training.py", line 912, in _fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "D:\Anaconda2\lib\site-packages\keras\callbacks.py", line 76, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "D:\Anaconda2\lib\site-packages\keras\callbacks.py", line 373, in on_epoch_end
    self.model.save(filepath, overwrite=True)
  File "D:\Anaconda2\lib\site-packages\keras\engine\topology.py", line 2630, in save
    save_model(self, filepath, overwrite)
  File "D:\Anaconda2\lib\site-packages\keras\models.py", line 52, in save_model
    'config': model.get_config()
  File "D:\Anaconda2\lib\site-packages\keras\engine\topology.py", line 2541, in get_config
    return copy.deepcopy(config)
  File "D:\Anaconda2\lib\copy.py", line 163, in deepcopy
    y = copier(x, memo)
File "D:\Anaconda2\lib\copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "D:\Anaconda2\lib\copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "D:\Anaconda2\lib\copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "D:\Anaconda2\lib\copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "D:\Anaconda2\lib\copy.py", line 328, in _reconstruct
    args = deepcopy(args, memo)
  File "D:\Anaconda2\lib\copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "D:\Anaconda2\lib\copy.py", line 237, in _deepcopy_tuple
    y.append(deepcopy(a, memo))
RuntimeError: maximum recursion depth exceeded

`
Could version be a problem? What versions should be used?

Thank you!

**Comment by jys5609** [comment]
Hi, I'm sorry for late reply.

Maybe it seems the problem with version.

The code was written in last year, so I used theano version 0.8.2 and keras version 1.0.6 and python 2.7

Maybe it works if you change the keras version. 

Thank you!
